name: rental_management_app
description: Mobile app for rental property management with role-based access
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  pull_to_refresh: ^2.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking & API
  dio: ^5.4.0
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  jwt_decoder: ^2.0.1
  
  # Routing
  go_router: ^12.1.3
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Date & Time
  intl: ^0.19.0
  
  # Charts (for reports)
  fl_chart: ^0.65.0
  
  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Images
  image_picker: ^1.0.7
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Utils
  logger: ^2.0.2+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
